# Generated by Django 4.0.6 on 2023-07-23 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0004_alter_feedback_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='feedbacker',
        ),
    ]
