# Generated by Django 4.0.6 on 2023-07-23 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0005_rename_name_feedback_feedbacker'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedback',
            new_name='WebsiteFeedback',
        ),
    ]
